// Generated by build.rs from ../../abi/*.json; do not edit the sibling files.
#[rustfmt::skip]
#[allow(clippy::all, dead_code)]
pub mod registry;
#[rustfmt::skip]
#[allow(clippy::all, dead_code)]
pub mod router;
#[rustfmt::skip]
#[allow(clippy::all, dead_code)]
pub mod executor;
#[rustfmt::skip]
#[allow(clippy::all, dead_code)]
pub mod aqua;
#[rustfmt::skip]
#[allow(clippy::all, dead_code)]
pub mod market;
