// @generated
// This file is @generated by prost-build.
/// Every event Horizon's own contracts emitted in one block, in log order. Addresses and hashes
/// are 0x-prefixed lower-case hex; uint256 values are decimal strings, as everywhere in Horizon.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HorizonEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<HorizonEvent>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HorizonEvent {
    /// MARKET_CREATED | CURVE_FILLED | ROUTE_EXECUTED | STRATEGY_ADMITTED | SHIPPED | DOCKED |
    /// COLLATERAL_CHANGED | MARKET_RESOLVED
    #[prost(string, tag="1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub contract: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub block_timestamp: u64,
    #[prost(string, tag="6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="7")]
    pub log_index: u32,
    #[prost(uint32, tag="8")]
    pub tx_index: u32,
    #[prost(oneof="horizon_event::Data", tags="10, 11, 12, 13, 14, 15, 16, 17")]
    pub data: ::core::option::Option<horizon_event::Data>,
}
/// Nested message and enum types in `HorizonEvent`.
pub mod horizon_event {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag="10")]
        MarketCreated(super::MarketCreated),
        #[prost(message, tag="11")]
        CurveFilled(super::CurveFilled),
        #[prost(message, tag="12")]
        RouteExecuted(super::RouteExecuted),
        #[prost(message, tag="13")]
        StrategyAdmitted(super::StrategyAdmitted),
        #[prost(message, tag="14")]
        Shipped(super::Shipped),
        #[prost(message, tag="15")]
        Docked(super::Docked),
        #[prost(message, tag="16")]
        CollateralChanged(super::CollateralChanged),
        #[prost(message, tag="17")]
        MarketResolved(super::MarketResolved),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketCreated {
    #[prost(string, tag="1")]
    pub creation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub resolver: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub yes_token: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub no_token: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub close_at: u64,
    #[prost(string, tag="7")]
    pub question: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub rules: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub evidence_source: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CurveFilled {
    #[prost(string, tag="1")]
    pub order_hash: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub shares: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub total_filled: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RouteExecuted {
    #[prost(string, tag="1")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub taker: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(bool, tag="4")]
    pub is_yes: bool,
    #[prost(bool, tag="5")]
    pub is_buy: bool,
    #[prost(string, tag="6")]
    pub shares: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub fills: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyAdmitted {
    #[prost(string, tag="1")]
    pub order_hash: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub commitment: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub committed_before: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub spendable: ::prost::alloc::string::String,
}
/// Aqua publication addressed to the Horizon router. The strategy bytes are the router's own
/// encoding; the consumer decodes them through the router, exactly as the Subgraph does.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Shipped {
    #[prost(string, tag="1")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub strategy_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub strategy: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Docked {
    #[prost(string, tag="1")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub strategy_hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollateralChanged {
    #[prost(string, tag="1")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub collateral: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketResolved {
    #[prost(string, tag="1")]
    pub market: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub result: u32,
    #[prost(string, tag="3")]
    pub resolver: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub evidence: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
