// Regenerated by `substreams protogen ./substreams.yaml --exclude-paths="sf/substreams,google"`.
// @generated
pub mod horizon {
    // @@protoc_insertion_point(attribute:horizon.v1)
    pub mod v1 {
        include!("horizon.v1.rs");
        // @@protoc_insertion_point(horizon.v1)
    }
}
